config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :create, :new, :edit, :update] do
    member do
      get :followings
      get :followers
      get :likes
      get :clips
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  
  resources :artists, only: [:index, :show]
  
  resources :albums, only: [:index, :show] 
  
  resources :reviews
  post "reviews/:id/update" => "posts#update"
  
  resources :favorites, only: [:create, :destroy]
  
  resources :clips, only: [:create, :destroy]
  
  
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  validates :introduce, length: { maximum: 500 }
  
  has_secure_password
  
  mount_uploader :image, ImageUploader
  
  has_many :reviews
  has_many :albums, through: :reviews
  
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverses_of_relationship, source: :user
  
  has_many :favorites
  has_many :favreviews, through: :favorites, source: :review
  
  has_many :clips
  has_many :clip_albums, through: :clips, source: :album
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end
  
  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
  
  def feed_reviews
    Review.where(user_id: self.following_ids + [self.id])
  end
  
  def like(review)
    favorites.find_or_create_by(review_id: review.id)
  end

  #お気に入り削除
  def unlike(review)
    favorite = favorites.find_by(review_id: review.id)
    favorite.destroy if favorite
  end

  #お気にり登録判定
  def favreview?(review)
    self.favreviews.include?(review)
  end
  
  #クリップメソッド
  def clip(album)
    clips.find_or_create_by(album_id: album.id)
  end
  
  #クリップ削除
  def unclip(album)
    clip = clips.find_by(album_id: album.id)
    clip.destroy if clip
  end
  
  #クリップ登録判定
  def clip_album?(album)
    self.clip_albums.include?(album)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :edit, :update, :followings, :followers]
  before_action :correct_user, only: [:edit, :update]
  
  def index
    @users = User.order(id: :desc).page(params[:page]).per(24)
  end

  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews.order(id: :desc).page(params[:page])
    counts(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    
    if current_user == @user
      if @user.update(user_params)
        flash[:success] = 'ユーザー情報を編集しました。'
        render :edit
      else
        flash.now[:danger] = 'ユーザー情報の編集に失敗しました。'
        render :edit
      end   
      
    else
      redirect_to root_url
    end
  end
  
  def followings
    @user = User.find(params[:id])
    @followings = @user.followings.page(params[:page])
    counts(@user)
  end
  
  def followers
    @user = User.find(params[:id])
    @followers = @user.followers.page(params[:page])
    counts(@user)
  end  
  
  def likes
    @user = User.find(params[:id])
    @favreviews = @user.favreviews.page(params[:page])
    @reviews = @user.reviews.order(id: :desc).page(params[:page])
    counts(@user)
  end
  
  def clips
    @user = User.find(params[:id])
    @clip_albums = @user.clip_albums.page(params[:page])
    @albums = @user.albums.order(id: :desc).page(params[:page])
    counts(@user)
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :introduce)
  end

  # 正しいユーザーかどうか確認
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user == current_user
  end
  
end

app/views/users/_users.html.erb
<% if users.any? %>

<div class="album py-5 bg-light">
  <div class="container">

    <div class="row" >
      <% users.each do |user| %>
        <div class="col-md-6">
          <div class="card mb-4 shadow-sm">
           <!--%= image_tag user.image.thumb200.url, class: "card-img-top" %-->
            <div class="card-body">
              <%= link_to user_path(user) do %>
              <%= image_tag user.image.thumbicon.url, class: "rounded-circle" %>
              <% end %>
              <span class="mb-4 ml-1"><%= link_to user.name, user_path(user) %></span>　
              <div class="inline-block-follow"><%= render 'relationships/follow_button', user: user %></div>
              <p class="mt-1 mb-0"> Followings: <%= user.followings.count %></p>
              <p class="mb-1"> Followers: <%= user.followers.count %></p>
              <p class="mt-1"><%= user.introduce %></p>
              
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= paginate users %>
<% end %>

app/views/users/clips.html.erb
<div class="jumbotron jumbotron-fluid jumbotron-user" style="background-image:url(<%= asset_path "user1.jpg" %>)">

<nav aria-label="breadcrumb">
  <ol class="breadcrumb breadcrumb-user">
	  <li class="breadcrumb-item"><a href="/">Top</a></li>
    <li class="breadcrumb-item"><i class="fas fa-users"></i> <a href=<%=users_path%>>Users</a></li>
    <li class="breadcrumb-item active" aria-current="page"><i class="fas fa-user"></i> <%= @user.name%>'s Clips</li>
  </ol>
</nav>


  <div class="media col-sm-12 mb-2 mt-1 " >
    <div class="media-left">
      <%= image_tag @user.image.thumb100.url, class: "img-thumbnail" %>
    </div>
    <div class="media-body media-body-user ml-4">
      <h3 class="media-heading"><%= @user.name %></h3>
      <p class="mt-0"><%= @user.introduce %></p>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </div>
</div>  

<div class="row">
  <div class="col-sm-12">
    <ul class="nav nav-tabs nav-justified mt-4 mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>"><i class="fas fa-compact-disc"></i> Reviews <span class="badge badge-secondary"><%= @count_reviews %></span></a></li>
      <li class="nav-item"><a href="<%= clips_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(clips_user_path(@user)) %>"><i class="fas fa-paperclip"></i> Clips <span class="badge badge-secondary"><%= @count_clips %></span></a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>"><i class="fas fa-user-friends"></i> Followings  <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>"><i class="fas fa-user-friends"></i> Followers  <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>"><i class="fas fa-heart"></i> Likes  <span class="badge badge-secondary"><%= @count_favreviews %></span></a></li>
    </ul>
    <%= render 'albums/albums', albums: @clip_albums %>
  </div>
</div>  
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<div class="text-center mb-2">
  <h3>プロフィール編集</h3>
</div>


<div class="row">
  <div class="col-sm-4 mt-4">
    <div class="card">
      <h7 class="card-header"><i class="fas fa-portrait"></i> プロフィール画像</h7>
      <div class="card-body">
        <%= form_with(model: @user, local: true) do |f| %>
          <%= render 'layouts/error_messages', model: f.object %>
          <%= image_tag @user.image.url, class: "card-img-top" %>
          <%= f.file_field :image, id: :user_image, class: 'form-control mt-1' %>
          <%= f.submit '編集完了', class: 'btn btn-info btn-block mt-2' %>
        <% end %>
      </div>
    </div>
  </div>
  
  <div class="col-sm-6 offset-sm-1">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :introduce, 'プロフィール(500文字未満)' %>
        <%= f.text_area :introduce, :maxlength => "500", :size => "80x5",  class: 'form-control' %>
      </div>

      <%= f.submit 'プロフィール編集を完了する', class: 'btn btn-info btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<div class="jumbotron jumbotron-fluid jumbotron-user" style="background-image:url(<%= asset_path "user1.jpg" %>)">

<nav aria-label="breadcrumb">
  <ol class="breadcrumb breadcrumb-user">
	  <li class="breadcrumb-item"><a href="/">Top</a></li>
    <li class="breadcrumb-item"><i class="fas fa-users"></i> <a href=<%=users_path%>>Users</a></li>
    <li class="breadcrumb-item active" aria-current="page"><i class="fas fa-user"></i> <%= @user.name%>'s Followers</li>
  </ol>
</nav>


  <div class="media col-sm-12 mb-2 mt-1 " >
    <div class="media-left">
      <%= image_tag @user.image.thumb100.url, class: "img-thumbnail" %>
    </div>
    <div class="media-body media-body-user ml-4">
      <h3 class="media-heading"><%= @user.name %></h3>
      <p class="mt-0"><%= @user.introduce %></p>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </div>
</div>  

<div class="row">
  <div class="col-sm-12">
    <ul class="nav nav-tabs nav-justified mt-4 mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>"><i class="fas fa-compact-disc"></i> Reviews <span class="badge badge-secondary"><%= @count_reviews %></span></a></li>
      <li class="nav-item"><a href="<%= clips_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(clips_user_path(@user)) %>"><i class="fas fa-paperclip"></i> Clips <span class="badge badge-secondary"><%= @count_clips %></span></a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>"><i class="fas fa-user-friends"></i> Followings  <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>"><i class="fas fa-user-friends"></i> Followers  <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>"><i class="fas fa-heart"></i> Likes  <span class="badge badge-secondary"><%= @count_favreviews %></span></a></li>
    </ul>
    <%= render 'users', users: @followers %>
  </div>
</div>
</div>

app/views/users/followings.html.erb
<div class="jumbotron jumbotron-fluid jumbotron-user" style="background-image:url(<%= asset_path "user1.jpg" %>)">

<nav aria-label="breadcrumb">
  <ol class="breadcrumb breadcrumb-user">
	  <li class="breadcrumb-item"><a href="/">Top</a></li>
    <li class="breadcrumb-item"><i class="fas fa-users"></i> <a href=<%=users_path%>>Users</a></li>
    <li class="breadcrumb-item active" aria-current="page"><i class="fas fa-user"></i> <%= @user.name%>'s Followings</li>
  </ol>
</nav>


  <div class="media col-sm-12 mb-2 mt-1 " >
    <div class="media-left">
      <%= image_tag @user.image.thumb100.url, class: "img-thumbnail" %>
    </div>
    <div class="media-body media-body-user ml-4">
      <h3 class="media-heading"><%= @user.name %></h3>
      <p class="mt-0"><%= @user.introduce %></p>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </div>
</div>  

<div class="row">
  <div class="col-sm-12">
    <ul class="nav nav-tabs nav-justified mt-4 mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>"><i class="fas fa-compact-disc"></i> Reviews <span class="badge badge-secondary"><%= @count_reviews %></span></a></li>
      <li class="nav-item"><a href="<%= clips_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(clips_user_path(@user)) %>"><i class="fas fa-paperclip"></i> Clips <span class="badge badge-secondary"><%= @count_clips %></span></a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>"><i class="fas fa-user-friends"></i> Followings  <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>"><i class="fas fa-user-friends"></i> Followers  <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>"><i class="fas fa-heart"></i> Likes  <span class="badge badge-secondary"><%= @count_favreviews %></span></a></li>    
    </ul>
    <%= render 'users', users: @followings %>
  </div>
</div>
</div>

app/views/users/index.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
	  <li class="breadcrumb-item"><a href="/">Top</a></li>
    <li class="breadcrumb-item active" aria-current="page"><i class="fas fa-users"></i> Users</li>
  </ol>
</nav>

<div class="text-center p-3">
  <h2>ユーザー一覧</h2>
</div>

<%= render 'users', users: @users %>

app/views/users/likes.html.erb
<div class="jumbotron jumbotron-fluid jumbotron-user" style="background-image:url(<%= asset_path "user1.jpg" %>)">

<nav aria-label="breadcrumb">
  <ol class="breadcrumb breadcrumb-user">
	  <li class="breadcrumb-item"><a href="/">Top</a></li>
    <li class="breadcrumb-item"><i class="fas fa-users"></i> <a href=<%=users_path%>>Users</a></li>
    <li class="breadcrumb-item active" aria-current="page"><i class="fas fa-user"></i> <%= @user.name%>'s Likes</li>
  </ol>
</nav>


  <div class="media col-sm-12 mb-2 mt-1 " >
    <div class="media-left">
      <%= image_tag @user.image.thumb100.url, class: "img-thumbnail" %>
    </div>
    <div class="media-body media-body-user ml-4">
      <h3 class="media-heading"><%= @user.name %></h3>
      <p class="mt-0"><%= @user.introduce %></p>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </div>
</div>  
  
<div class="row">
  <div class="col-sm-12">
    <ul class="nav nav-tabs nav-justified mt-4 mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>"><i class="fas fa-compact-disc"></i> Reviews <span class="badge badge-secondary"><%= @count_reviews %></span></a></li>
      <li class="nav-item"><a href="<%= clips_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(clips_user_path(@user)) %>"><i class="fas fa-paperclip"></i> Clips <span class="badge badge-secondary"><%= @count_clips %></span></a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>"><i class="fas fa-user-friends"></i> Followings  <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>"><i class="fas fa-user-friends"></i> Followers  <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>"><i class="fas fa-heart"></i> Likes  <span class="badge badge-secondary"><%= @count_favreviews %></span></a></li>
    </ul>
    <%= render 'reviews/reviews', reviews: @favreviews %>
  </div>
</div> 
</div>

app/views/users/new.html.erb
<div class="jumbotron jumbotron-fluid jumbotron-top" style="background-image:url(<%= asset_path "top1.jpg" %>)">
<div class="text-center">
  <h1 class="signuptitle">Sign up</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      
      <div class="form-group">
        <%= f.label :image, 'プロフィール画像' %>
        <%= f.file_field :image, class: 'form-control' %>
      </div>
      
      <%= f.submit 'Sign up', class: 'btn btn-info btn-block' %>
    <% end %>
  </div>
</div>
</div>

app/views/users/show.html.erb
<div class="jumbotron jumbotron-fluid jumbotron-user" style="background-image:url(<%= asset_path "user1.jpg" %>)">

<nav aria-label="breadcrumb">
  <ol class="breadcrumb breadcrumb-user">
	  <li class="breadcrumb-item"><a href="/">Top</a></li>
    <li class="breadcrumb-item"><i class="fas fa-users"></i> <a href=<%=users_path%>>Users</a></li>
    <li class="breadcrumb-item active" aria-current="page"><i class="fas fa-user"></i> <%= @user.name%>'s Reviews</li>
  </ol>
</nav>


  <div class="media col-sm-12 mb-2 mt-1 " >
    <div class="media-left">
      <%= image_tag @user.image.thumb100.url, class: "img-thumbnail" %>
    </div>
    <div class="media-body media-body-user ml-4">
      <h3 class="media-heading"><%= @user.name %></h3>
      <p class="mt-0"><%= @user.introduce %></p>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </div>
</div>  

<div class="row">
  <div class="col-sm-12">
    <ul class="nav nav-tabs nav-justified mt-4 mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>"><i class="fas fa-compact-disc"></i> Reviews <span class="badge badge-secondary"><%= @count_reviews %></span></a></li>
      <li class="nav-item"><a href="<%= clips_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(clips_user_path(@user)) %>"><i class="fas fa-paperclip"></i> Clips <span class="badge badge-secondary"> <%= @count_clips %></span></a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followings_user_path(@user)) %>"><i class="fas fa-user-friends"></i> Followings  <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(followers_user_path(@user)) %>"><i class="fas fa-user-friends"></i> Followers  <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>"><i class="fas fa-heart"></i> Likes <span class="badge badge-secondary"> <%= @count_favreviews %></span></a></li>
    </ul>
    <%= render 'reviews/reviews', reviews: @reviews %>
  </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>