config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :create, :new, :edit, :update] do
    member do
      get :followings
      get :followers
      get :likes
      get :clips
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  
  resources :artists, only: [:index, :show]
  
  resources :albums, only: [:index, :show] 
  
  resources :reviews
  post "reviews/:id/update" => "posts#update"
  
  resources :favorites, only: [:create, :destroy]
  
  resources :clips, only: [:create, :destroy]
  
  
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    
    if logged_in?
      @review = current_user.reviews.build
      @reviews = current_user.feed_reviews.order(id: :desc).page(params[:page])
    end
  end
end

app/views/toppages/index.html.erb
<% if logged_in? %>
  <div class="text-center p-3">
    <h2>タイムライン</h2>
  </div>
  <!--<div class="row">-->

    <!--<div class="col-sm-12">-->
      <%= render 'reviews/reviews', reviews: @reviews %>
    <!--</div>-->
  <!--</div>-->
<% else %>
  
  <div class="jumbotron jumbotron-fluid jumbotron-top" style="background-image:url(<%= asset_path "top1.jpg" %>)">
    <div class="container-fluid">
      <div class="text-center">
        <h5>ー「音楽」を記録して繋がろうー</h5>
        <h1 class="welcome mb-3">Discnote</h1>
        <%= link_to 'Sign up now!', signup_path, class: 'btn btn btn-info' %>
        <%= link_to 'Login', login_url, class: 'btn btn btn-outline-info' %>
      </div>
    </div>
  </div>
<% end %>