config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :create, :new, :edit, :update] do
    member do
      get :followings
      get :followers
      get :likes
      get :clips
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  
  resources :artists, only: [:index, :show]
  
  resources :albums, only: [:index, :show] 
  
  resources :reviews
  post "reviews/:id/update" => "posts#update"
  
  resources :favorites, only: [:create, :destroy]
  
  resources :clips, only: [:create, :destroy]
  
  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy, :edit]
  
  def index
  end

  def show
  end

  def new
  end

  def create
    @album = Album.find(review_params[:album_id])
    @review = current_user.reviews.build(review_params)
    if @review.save
      flash[:success] = 'レビューを投稿しました。'
      redirect_to album_path(@album)
    else
      @reviews = current_user.feed_reviews.order(id: :desc).page(params[:page])
      flash.now[:danger] = 'レビューの投稿に失敗しました。'
      render 'albums/show'
    end
  end
  
  def edit
    @review = current_user.reviews.find_by(id: params[:id])
    
  end

  def update
    @review = current_user.reviews.find_by(id: params[:id])
    if @review.user_id == current_user.id
      if @review.update(review_params)
        flash[:success] = 'レビューを更新しました。'
        render :edit
      else
        flash.now[:danger] = 'ユーザー情報の編集に失敗しました。'
        render :edit
      end  
    else
      redirect_to root_url
    end
  end

  def destroy
    @review.destroy
    flash[:success] = 'レビューを削除しました。'
    redirect_back(fallback_location: root_url)
  end
  
  private
  
  def review_params
    params.require(:review).permit(:album_id, :body, :rate)
  end
  
  def correct_user
    @review = current_user.reviews.find_by(id: params[:id])
    unless @review
      redirect_to root_url
    end
  end
  
end

app/views/reviews/_reviews.html.erb
<% if reviews.any? %>
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
      <% reviews.each do |review| %>
        <div class="col-lg-6 ">
          <div class="card flex-row mb-4 shadow-sm">
            <div class="card-body d-flex flex-column align-items-start">
              <div class="flex-row">
                <% unless (controller.controller_name == "users" && controller.action_name == "show") %>
                  <%= link_to user_path(review.user) do %>
                  <%= image_tag review.user.image.thumbicon.url, class: "rounded-circle" %>
                  <% end %>
                  <span class="d-inline-block mb-4"><%= link_to review.user.name, user_path(review.user) %>のレビュー</span>
                <% end %>
              </div>

              <% unless (controller.controller_name == "albums" && controller.action_name == "show") %>
                <h5 class="card-subtitle mt-2 mb-1"><%=link_to review.album.title, album_path(review.album) %></h5>
                <p class="card-subtitle"><%= link_to review.album.artist.name, artist_path(review.album.artist) %></p>
              <% end %>
              
              <!--評価-->

              <!--h6 class="ml-3 mt-3">Rate：<!--%= review.rate %--><!--/h6-->
              <div class="mb-2" id="star-<%= review.id %>">Rate：<%= review.rate.round(1) %></div>
              <%= javascript_include_tag "jquery.raty.js" %>

              
              
                <script>
                  $('#star-<%= review.id %>').raty({
                    size: 36,
                    starOff:  '<%= asset_path('star-off.png') %>',
                    starOn : '<%= asset_path('star-on.png') %>',
                    starHalf: '<%= asset_path('star-half.png') %>',
                    
                    half: true,
                    readOnly: true,
                    score: <%= review.rate %>,
                  });
                </script>  
              
              
              <p class="card-text review-body"><%= review.body %></p>
              <!--button type="button" class="btn btn-sm btn-outline-secondary"--><!--%= link_to 'view', review_path(review) %></button-->
              <% if logged_in? %>
                <div class="mt-1">
                  <%= render 'favorites/like_button', review: review %>
                </div>
              <% end %>
              <p class="text-muted mt-1 mb-0 align-items-end">posted at <%= review.created_at %></p>
              <div class="align-items-end">
                <% if current_user == review.user %>
                  <%= link_to "Delete", review, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-outline-danger btn-sm align-items-end' %>
                  <%= link_to "Edit", "/reviews/#{review.id}/edit", method: :get, class: 'btn btn-outline-dark btn-sm align-items-end' %>
                <% end %>
              </div>
            </div>
            <% unless (controller.controller_name == "albums" && controller.action_name == "show") %>
            <div class="card-img-right align-items-start flex-auto img-responsive mt-4 mr-2">
              <%= link_to album_path(review.album) do %>
              <%= image_tag review.album.image.thumb200.url, class: "border img-fluid review-img" %>
              <% end %>
              <div class="mt-1 mb-2 btn-sm flex-fill p-0">
                <%= render 'clips/clip_button', album: review.album, class: "" %>
              </div>
            </div>
            <% end %>
            
          </div>
        </div>
      <% end %>
      
      
    </div>
  </div>
</div>

<% end %>
<%= paginate @reviews %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/edit.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
	  <li class="breadcrumb-item"><a href="/">Top</a></li>
		<li class="breadcrumb-item active" aria-current="page"><i class="fas fa-edit"></i> Edit</li>
	</ol>
</nav>

<div class="text-center p-3">
  <h3>レビュー編集</h3>
</div>

<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
        <div class="col-lg-12">
          <div class="card flex-row mb-4 shadow-sm">
            <div class="card-body ">
              <div class="flex-row">
                <% unless (controller.controller_name == "users" && controller.action_name == "show") %>
                  <%= link_to user_path(@review.user) do %>
                  <%= image_tag @review.user.image.thumbicon.url, class: "rounded-circle" %>
                  <% end %>
                  <span class="d-inline-block mb-4"><%= link_to @review.user.name, user_path(@review.user) %>のレビュー</span>
                <% end %>
              </div>

              <% unless (controller.controller_name == "albums" && controller.action_name == "show") %>
                <h5 class="card-subtitle mt-2 mb-1"><%=link_to @review.album.title, album_path(@review.album) %></h5>
                <p class="card-subtitle"><%= link_to @review.album.artist.name, artist_path(@review.album.artist) %></p>
              <% end %>
              
              
            <%= form_with(model: @review, local: true) do |f| %>
              <!--評価-->
              <div class="form-group review-form">
                <label for="rate" class="d-inline-block">Rate： <%= @review.rate.round(1) %></label>
                <div id="star" class="d-inline-block"></div>
                <div class="ml-1", id="star_input" style="height: 1.5em; width: 2em;">
                <%= f.hidden_field :rate, id: :review_star %>
                <%= javascript_include_tag "jquery.raty.js" %>
                </div>
              </div>
         
              <!-- 評価javascript -->
              <script>
              $('#star').raty({
            
                size     : 36,
                starOff:  '<%= asset_path('star-off.png') %>',
                starOn : '<%= asset_path('star-on.png') %>',
                starHalf: '<%= asset_path('star-half.png') %>',
                scoreName: 'review[rate]',
            
                target: '#star_input',
                targetType: 'number',
                targetKeep: true, 
                half: true,
          　     precision:true,
              　round : { down: .4, full: .6, up: .99 },
                hints: ['1', '2', '3', '4', '5']
              });
          
              </script> 
              
              
              <div class="form-group">
                <%= f.text_area :body,placeholder: "レビュー編集", rows:7, class: 'mt-1 form-control input-lg' %>
              </div>
              <%= f.submit 'Update', class: 'mt-0 mb-3 btn btn-info  btn-md' %>
            <% end %>
            
              
              <p class="text-muted mt-1 mb-0 align-items-end">posted at <%= @review.created_at %></p>
              <div class="align-items-end">
                <% if current_user == @review.user %>
                  <%= link_to "Delete", @review, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-outline-danger btn-sm align-items-end' %>
                <% end %>
              </div>
            </div>
            <% unless (controller.controller_name == "albums" && controller.action_name == "show") %>
            <div class="card-img-right align-items-start flex-auto img-responsive mt-4 mr-2">
              <%= link_to album_path(@review.album) do %>
              <%= image_tag @review.album.image.thumb200.url, class: "border img-fluid review-img" %>
              <% end %>
            </div>
            <% end %>
            
          </div>
        </div>

    </div>
</div>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/reviews/update.html.erb
<h1>Reviews#update</h1>
<p>Find me in app/views/reviews/update.html.erb</p>