config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :create, :new, :edit, :update] do
    member do
      get :followings
      get :followers
      get :likes
      get :clips
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  
  resources :artists, only: [:index, :show]
  
  resources :albums, only: [:index, :show] 
  
  resources :reviews
  post "reviews/:id/update" => "posts#update"
  
  resources :favorites, only: [:create, :destroy]
  
  resources :clips, only: [:create, :destroy]
  
  
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-md navbar-dark bg-info">
    <a class="navbar-brand" href="/"><i class="fas fa-headphones-alt"></i> Discnote</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><i class="fas fa-music"></i> Music</a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to albums_path do %><i class="fas fa-compact-disc"></i> Albums<% end %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to artists_path do %><i class="fas fa-guitar"></i> Artists<% end %></li>
            </ul>
          <li class="nav-item"><%= link_to users_path, class: 'nav-link' do %><i class="fas fa-users"></i> Users<% end %></li>
          <li class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><i class="fas fa-user-circle"></i> <%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right"> 
              <li class="dropdown-item"><%= link_to user_path(current_user) do %><i class="fas fa-id-card"></i> My Profile<% end %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to edit_user_path(current_user) do %><i class="fas fa-user-cog"></i> Edit Profile<% end %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to logout_path, method: :delete do %><i class="fas fa-sign-out-alt"></i> Logout<% end %></li>
            </ul>
          </li>
        <% else %>
          <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><i class="fas fa-music"></i> Music</a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to albums_path do %><i class="fas fa-compact-disc"></i> Albums<% end %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to artists_path do %><i class="fas fa-guitar"></i> Artists<% end %></li>
            </ul>
          <li class="nav-item"><%= link_to signup_path, class: 'nav-link' do %><i class="fas fa-user-edit"></i> Signup<% end %></li>
          <li class="nav-item"><%= link_to login_path, class: 'nav-link' do %><i class="fas fa-sign-in-alt"></i> Login<% end %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Discnote</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <!--%= javascript_include_tag "jquery-3.3.1.min" %-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
 
  <style>
  /* スマホ横画面用 */
  @media screen and (max-width: 480px) {
    .container{padding:0}
    div[class^="col-"] {padding:0}
    .row {margin:0;}
  }
  /* スマホ縦画面用 */
  @media screen and (max-width: 320px) {
    .container{padding:0}
    div[class^="col-"] {padding:0}
    .row {margin:0;}
  }
  </style>
    
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      
      <%= yield %>
    </div>
  </body>
</html>